### ISSUE TITLE
Invalid range

### ISSUE THREAD

**Issue by orangewait** [solarwinds/swo-cli#21]
Hi, I have the following setup:

- Version: swo-cli_windows_amd64.zip, version 1.3.4 (https://github.com/solarwinds/swo-cli/releases/tag/v1.3.4)
- Windows Fuse: UTC+01:00

The output of all these commands:

	swo logs get mypattern
	swo logs get --min-time 'one hour ago' myPattern
	swo logs get --min-time 'one hour ago' --max-time 'one minute ago' myPattern
	swo logs get --min-time '2024-09-27 11:40' --max-time '2024-09-27 11:42' myPattern
	swo logs get --min-time '2024-09-27 10:40 UTC' --max-time '2024-09-27 10:42 UTC' myPattern

always ends with the following **Invalid range** error:

	2024/09/27 12:46:03 Received non-2xx status code: 400, response body: 
	{
		"error": {
			"code": "BadArgument",
			"message": "Invalid range: [2024-09-27T10:46:04Z..2024-09-27T10:46:03.799Z]",
			"target": "",
			"details": null,
			"innerError": null
		}
	}

I'm sorry, as of now I don't know golang.
I just wanted to let you know that this problem exists.

Thanks

**Comment by grepory** [comment]
@orangewait A backend problem caused this error to be returned on the last page of search results. I'm sorry if this caused confusion. Thanks for reporting it!
